### PR TITLE
Add tensor values to TimeSeries

### PR DESCRIPTION
**Pull request by halterw**
TimeSeries now spit out the mean values of Tii, Eii, sxxd, szzd, sxz, exxd, ezzd, and exz.

### CODE REVIEW

**Comment by tduretz** [comment]
Hi William, can you add a couple of figures such that we have validation that it works? 
For example, you could compare evolution of stress components with that of the MATLAB script we use to benchmark anisotropy evolution.

**Comment by kulakovri** [comment]
@halterw I'm okay with this PR as long as analytical mass conservation solution works. Did you test the surface level changes?

**Review by tduretz — COMMENTED** [review]
Feel free to merge!

**Comment by tduretz** [comment]
@halterw and @kulakovri please can you also merge this one?

**Pull request merged**
