### PR TITLE
Fixed type incompatibility issue in crazy k.

### PR DESCRIPTION
**Pull request by lcandiot**
This fixes a pointer type incompatibility issue in the AddCrazyConductivity function.

### CODE REVIEW

**Comment by tduretz** [comment]
thanks for the contribution!

**Review by tduretz — COMMENTED** [review]
Looks all good to me. 
Not sure if this functionality was ever used in another setup.

**Review by tduretz — APPROVED** [review]

**Review by lcandiot — COMMENTED** [review]
> Looks all good to me. 
> Not sure if this functionality was ever used in another setup.  

I think it is used in several setups.

**Comment by tduretz** [comment]
We should maybe try one of those then.  Do you see which setups depend on it?

**Comment by lcandiot** [comment]
DoubleSubduction.c and CollisionIra.c both use Crazy conductivity.
QuartzCoesite.c calls MutateInput, too, but already as newly defined by my PR. So there should be no issue with QuartzCoesite.c

**Comment by tduretz** [comment]
perfect! thanks for having checked!

**Comment by lcandiot** [comment]
You are welcome!

**Pull request merged**
