### PR TITLE
Add stress preloading

### PR DESCRIPTION
**Pull request by mthielma**
This add the possibility to add initial stresses on the particles in the same way as e.g. initial temperatures can be prescribed. Homogeneous stresses can be prescribed in the input file and are then transferred to the particles (see Shrinking_preload.c).

### CODE REVIEW

**Comment by tduretz** [comment]
Thanks a lot for the contribution. This looks all fine to me. That a useful feature to include.

**Comment by tduretz** [comment]
I have not realised this was never merged. I thought you'd do so after the approval. Do you mind merging it?

**Comment by mthielma** [comment]
I would do so, but it seems I do not have write access.

**Comment by tduretz** [comment]
Should be good by now :D

**Pull request merged**
